import "./globals.css";
import Header from "./_components/Header";
import { Poppins } from "next/font/google";
import { Open_Sans } from "next/font/google";
import Footer from "./_components/Footer";

// Non variable fonts.
// you have to specify array of weight

const poppins = Poppins({
  weight: ["400", "900"],   
  display: "swap",
  subsets: ["latin"],
  variable: "--poppins-font",
});

// For variable fonts.
// you have to specify weight= "variable" value only.

const open_sans = Open_Sans({
  weight: "variable",
  style: ["italic", "normal"],
  display: "swap",
  subsets: ["latin"],
  variable: "--open-sans-font",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="md:px-20">
          <Header />
          {children}
          
        </div>

        <Footer />
        
        </body>
    </html>
  );
}