import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { Poppins, Open_Sans } from "next/font/google";
import { Toaster } from "sonner";

// Non-variable fonts
const poppins = Poppins({
  weight: ["400", "900"],
  display: "swap",
  subsets: ["latin"],
  variable: "--poppins-font",
});

// Variable fonts
const open_sans = Open_Sans({
  weight: "variable",
  style: ["italic", "normal"],
  display: "swap",
  subsets: ["latin"],
  variable: "--open-sans-font",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${open_sans.className}`}>
        <div className="md:px-20">
          <Header />
          {children}
          <Toaster />
        </div>
        <Footer />
      </body>
    </html>
  );
}